# Generated by Django 5.0 on 2024-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
